# Generated by Django 5.2.4 on 2025-09-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_listed', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='customeradm_name_942843_idx'), models.Index(fields=['created_at'], name='customeradm_created_218b1a_idx'), models.Index(fields=['is_deleted'], name='customeradm_is_dele_f196ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('sofa', 'Sofa'), ('chair', 'Chair'), ('table', 'Table'), ('bed', 'Bed'), ('storage', 'Storage'), ('accessories', 'Accessories')], default='sofa', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Enter percentage (e.g., 10 for 10%) or fixed amount', max_digits=10)),
                ('tax_type', models.CharField(choices=[('free', 'Tax Free'), ('taxable', 'Taxable')], default='free', max_length=20)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, help_text='VAT percentage (e.g., 18 for 18%)', max_digits=5)),
                ('stock_quantity', models.IntegerField()),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock falls below this number')),
                ('manage_stock', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('out-of-stock', 'Out of Stock'), ('low-stock', 'Low Stock')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='customeradm_status_efba44_idx'), models.Index(fields=['created_at'], name='customeradm_created_d3d8b9_idx'), models.Index(fields=['sku'], name='customeradm_sku_bda04d_idx'), models.Index(fields=['name'], name='customeradm_name_a05358_idx'), models.Index(fields=['is_deleted'], name='customeradm_is_dele_c26c5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customeradmin.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
