# Generated by Django 5.2.4 on 2025-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='When was product blocked', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='blocked_by',
            field=models.CharField(blank=True, help_text='Who blocked the product', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Block the product from customer view'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('out-of-stock', 'Out of Stock'), ('low-stock', 'Low Stock'), ('blocked', 'Blocked')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_blocked'], name='customeradm_is_bloc_f8cdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_blocked', 'status'], name='customeradm_is_bloc_9849cf_idx'),
        ),
    ]
