# Generated by Django 5.2.4 on 2026-01-12 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0003_returnitem_returnrequest_returnitem_return_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for admin reference', max_length=200)),
                ('image', models.ImageField(help_text='Recommended size: 1920x600px for hero banners', upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image', null=True, upload_to='banners/mobile/')),
                ('position', models.CharField(choices=[('hero', 'Hero Banner (Main)'), ('top', 'Top Banner'), ('middle', 'Middle Banner'), ('bottom', 'Bottom Banner'), ('sidebar', 'Sidebar Banner')], default='hero', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('heading', models.CharField(blank=True, help_text='Main banner text', max_length=200)),
                ('subheading', models.CharField(blank=True, help_text='Secondary text', max_length=300)),
                ('button_text', models.CharField(blank=True, help_text="Button text (e.g., 'Shop Now')", max_length=50)),
                ('button_link', models.URLField(blank=True, help_text='Button link URL')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to start showing')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing (optional)', null=True)),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of clicks')),
                ('impressions', models.PositiveIntegerField(default=0, help_text='Number of impressions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
    ]
