# Generated by Django 5.2.4 on 2025-10-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0003_order_orderitem_order_customeradm_order_i_0a0b7d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
