# Generated by Django 5.2.4 on 2026-01-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0004_banner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='customeradm_status_cdd43f_idx',
            old_name='customeradm_status_efba44_idx',
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='customeradmin.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False, 'is_listed': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='customeradmin.category'),
        ),
    ]
