# Generated by Django 5.2.4 on 2026-02-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0005_rename_customeradm_status_efba44_idx_customeradm_status_cdd43f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(help_text='e.g., Teak Wood, Sheesham, MDF, Plywood, Metal', max_length=100)),
                ('sku_suffix', models.CharField(blank=True, help_text="Added to product SKU, e.g., '-TEAK'", max_length=20)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for this variant (can be negative)', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='customeradmin.product')),
            ],
            options={
                'ordering': ['product', 'material'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='customeradm_product_bb6b5d_idx'), models.Index(fields=['stock_quantity'], name='customeradm_stock_q_27276a_idx')],
                'unique_together': {('product', 'material')},
            },
        ),
    ]
