# Generated by Django 5.2.4 on 2026-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0006_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
