# Generated by Django 5.2.4 on 2026-02-11 13:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeradmin', '0008_alter_banner_image_alter_banner_mobile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Recommended size: 1920x600px for hero banners', max_length=255, verbose_name='image'),
        ),
    ]
