# Generated by Django 5.2.4 on 2025-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_order_orderitem_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
