# Generated by Django 5.2.4 on 2026-01-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_banner'),
    ]

    operations = [
    ]
