# Generated by Django 5.2.4 on 2025-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_order_return_reason_order_returned_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.CharField(max_length=50),
        ),
    ]
