# Generated by Django 5.2.4 on 2026-02-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_cartitem_unique_together_cartitem_variant_and_more'),
        ('customeradmin', '0007_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected material variant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customeradmin.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product', 'variant')},
        ),
    ]
